<a href="https://colab.research.google.com/github/MLEngDeena/DataStructureAndAlgorithmUsingPython/blob/main/Two_Dimensional_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

TwoDArray = np.array ([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(TwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [3]:
newTwoDArray = np.insert (TwoDArray , 1 , [[1,2,3,4]] , axis = 0)
print(newTwoDArray)

[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [5]:
print(len(TwoDArray))

4


In [6]:
AnotherTwoDArray = np.append(TwoDArray , [[1,2,3,4]] , axis = 0)
print(AnotherTwoDArray)
print(len(AnotherTwoDArray))
print(len(AnotherTwoDArray[0]))

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]
5
4


Access Element

In [7]:
def accessElements(array,rowIndex, colIndex):
  if rowIndex >= len(array) and colIndex >= len(array[0]):
    print("Incorrect Index")
  else:
    print(array[rowIndex][colIndex])



accessElements(AnotherTwoDArray,1,2)

11


Traverse the complete Array

In [9]:
def traverseTDAray(array):
  for i in range (len(array)):
    for j in range (len(array[0])):
      print(array[i][j])

traverseTDAray(TwoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


Search in TWo Dimensional Array

In [11]:
def SearchTDArray(array,value):
  for i in range(len(array)):
    for j in range(len(array[0])):
      if array[i][j] == value:
        return 'The value is located index '+str(i)+" "+str(j)
  return 'The element not found'

print(SearchTDArray(TwoDArray,12))

The value is located index 2 0


Deletion in Two Dimensional Array

In [12]:
newTwoDArray = np.delete(TwoDArray , 1 , axis=1)
print(newTwoDArray)

[[11 10  6]
 [10 11  5]
 [12 12  8]
 [15 14  9]]
